### ISSUE TITLE
Export custom dataset to Excel - Datagrid

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#187] opened 2018-09-19 22:33 UTC
**Describe the bug**
The specified custom dataset to datagrid.exportToExcel is ignored.

**To Reproduce**
1. In the demo project go to Datagrid Paging Service.
2. The code passes a list of 100 elements to exportToExcel
3. The excel sheet only has the 5 elements from current page of the datagrid.

**Expected behavior**
3. The excel sheet has all 100 elements passed to exportToExcel

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
 - ids-enterprise-ng Version: 4.10.1

**Comment by tmcconechy** [comment] 2018-09-20 00:35
If you want to just send the dataset directly i exposed the api separate in a way you can pass the dataset. We shouldn't any longer pass anymore into the dataset export api, you can now use this API directly

https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-export-without-datagrid.html#L57

We may need to expose this api globally in the ng api.

**Comment by dmcodrum** [comment] 2018-09-20 12:56
Definitely needs to be exposed in ng api.

**Comment by tmcconechy** [comment] 2018-10-09 13:09
This seems to be a duplicate of #203 which was fixed on this pull request https://github.com/infor-design/enterprise-ng/pull/205

**Closed by tmcconechy** 2018-10-09 13:09 UTC
Labels: [3], for: up for grabs, type: bug
