### ISSUE TITLE
DropDown: Select Menu and Text Field in one

### ISSUE THREAD

**Issue by vamsibandarupalli** [infor-design/enterprise-ng#686] opened 2019-12-16 04:46 UTC
We have an requirement for DropDown and input text field in one. User should be able to select from dropdown or he may type in. 

We have "dropdown-typehead" where user can type in but, he can only select from dropdown.
https://latest-enterprise.demo.design.infor.com/components/dropdown/test-allow-custom-keystroke.html

**Comment by tmcconechy** [comment] 2019-12-16 14:28
We previously had this request. But we closed it as wont do. What you can do is use a text box and a dropdown separate. The problem is the interaction is too difficult with the filtering.

We think that a dropdown should just be a dropdown. But if you have a more concrete info on a use case lets make an issue following the template over in https://github.com/infor-design/enterprise/issues/new/choose

If more folks than a few need this we can later consider it again as it has come up two times now.

**Comment by tmcconechy** [comment] 2019-12-16 14:31
Older issue with some info (which was eventually rejected for implementation). https://jira.infor.com/browse/UXD-241

**Closed** 2019-12-24 20:58 UTC
Labels: [∞], status: wont fix :no_entry_sign:, type: enhancement :sparkles:
