### ISSUE TITLE
DataGrid: Calculates the required column width only for parent rows

### ISSUE THREAD

**Issue by prazny** [infor-design/enterprise-ng#1767] opened 2024-08-07 09:01 UTC
**Describe the bug**
The DataGrid calculates the required column width only for parent rows.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1801-9apghj?embed=1&file=src%2Fapp%2Fapp.component.html
2. First DataGrid has the longest description value for a child row, which is wrapped. The second DataGrid has the longest description value for a parent row, and all the values are properly displayed.

**Expected behavior**
Child rows should also be taken into account when calculating column widths.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/user-attachments/assets/908c0daa-fa2d-421f-86d3-0d263fc83510)

**Platform**
 - OS Version: Windows 11
 - Browser Name Chrome
 - Browser Version 127.0.6533.99 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2024-08-07 14:08
I think this is a duplicate of https://github.com/infor-design/enterprise/issues/8646

It actually does not do auto column width for tree because its too slow to calculate for large trees. But seeing if we can find a way. Lets follow that issue. Or start with a default width

-Tim

**Closed by tmcconechy** 2024-08-07 14:08 UTC
