### ISSUE TITLE
Dropdown: Specific dropdown inside the grid does not get disable.

### ISSUE THREAD

**Issue by gauravugale** [infor-design/enterprise-ng#667] opened 2019-11-19 09:47 UTC
**Describe the bug**
specific dropdown inside the grid does not get disable or readonly. if we try to achieve this, all dropdown get disable or readonly. 

**To Reproduce**
1. add dropdown in grid using **editor: Soho.Editors.Dropdown** 
2. try to set readonly on the condition (attachment 3 and 4), but all the dropdown get disable/ readonly (attachment 2)

**Expected behavior**
it should be get disable or readonly. 

**Version**
- ids-enterprise-ng: [e.g. v5.5.2]

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/50131562/69209993-58fdc680-0b7f-11ea-96e6-6681048cc761.JPG)

![Capture2](https://user-images.githubusercontent.com/50131562/69210085-a37f4300-0b7f-11ea-9f65-8f1cbc966a5f.JPG)

![Capture21](https://user-images.githubusercontent.com/50131562/69210344-7b441400-0b80-11ea-9329-3b793356a68e.JPG)

![Capture22](https://user-images.githubusercontent.com/50131562/69210352-84cd7c00-0b80-11ea-9d69-0f046290e7bd.JPG)

**Platform**
 - OS Version: Windows 10
 - Browser Name [e.g. chrome, safari, IE]

**Comment by gauravugale** [comment] 2019-11-20 05:11
Hi Tim,

I want to set some grid dropdown as readonly on the basis condition. I have been added some more description and attachment for better understanding.

**Comment by tmcconechy** [comment] 2019-11-20 14:16
I think your doing this wrong. I tested this and its working... A better way would be to use isEditable.

1. Make a function with your logic
```
    var isDisabled = function(row, cell, value) {
      return (row % 2 === 0);
    }
```

yours might be
```
    var isDisabled = function(row, cell, value) {
      return (item.statusInt ===  4);
    }
```

2. Then attach this to the column `isEditable` , then this will run and you keep the formatter as is.

```
    columns.push({ id: 'action', name: 'Action', field: 'action', formatter: Formatters.Dropdown, editor: Editors.Dropdown, validate: 'required', isEditable: isDisabled});
```

You can maybe make yours work somehow. But this works as tested. As such this is not a bug so closing assuming this will work.

Hope That Helps!

**Closed by tmcconechy** 2019-11-20 14:16 UTC
Labels: [2], type: support :sos:
