### ISSUE TITLE
Use Library support in Angular CLI 6

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise-ng#155] opened 2018-08-13 12:05 UTC
**Problem.**
Current project does not publish artifacts that can be consumed directly via npm. To be able to use the project it forces me to build / compile the project before I can use it. This is not good since I can have  other dependencies (or versions of the dependencies) that enterprise-ng can not use. I might have  other compile settings in tsconfig.json that will stop me from compiling the enterprise-ng project. All these things makes it hard or impossible to use the project. 

**Solution**
Angular CLI 6 now supports creation of libraries by the use of [ng-packagr](https://www.npmjs.com/package/ng-packagr). You can now use a new attribute type _projectType_ and set the value to _library_ in angular.json.

Please take a look at the following wiki page for more information: https://github.com/angular/angular-cli/wiki/stories-create-library. By changing the project to a library this project will be much easier to consume since the artifacts published on npm can be consumed directly as any other Angular library published on npm.

**More info on Angular CLI 6 library support**
More information on the matter can be found in this blog for example: https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5

**Comment by tmcconechy** [comment] 2018-08-13 13:13
This is a duplicate of https://github.com/infor-design/enterprise-ng/issues/52
It actually has a pending pull request https://github.com/infor-design/enterprise-ng/pull/143 which you can try to review.

**Closed** 2018-08-13 13:13 UTC
Labels: type: enhancement

**Comment by ablomq** [comment] 2018-08-13 13:38
When do expect pull request #143 to be published?

**Comment by tmcconechy** [comment] 2018-08-13 13:40
I think its technically ready to merge but would like a few more reviewers to try it out so just waiting a little bit more. Will definitely be a part of this months release. Feel free to try it on the branch and see if it meets your expectations.
