### ISSUE TITLE
Input: the content cannot be selected on IE or Edge browser

### ISSUE THREAD

**Issue by zyhalj** [infor-design/enterprise-ng#288] opened 2018-12-09 12:00 UTC
**Describe the bug**
On IE or Edge browser, the content of Input component cannot be selected. Chrome is OK。

**To Reproduce**
If Input component has tooltips, it will be set a class “logpress-target” and its attribute “-ms-user-select” is none. This class disable the selection on Input component.
Once remove the tooltip, it can work.

**Expected behavior**
Tooltip is required to us, so please remove logpress-target class for Input component on IE and Edge.

**Version**
- ids-enterprise-ng: v4.9.0 ~ v4.12.1

**Screenshots**
![capture](https://user-images.githubusercontent.com/13767418/49696985-e48b7b00-fbec-11e8-94b5-288aa3900937.PNG)

**Platform**
•Device (if applicable) PC or laptop.
•OS Version: Windows 10
•Browser Name IE11 and Edge
•Browser Version IE11 version 11.1446.15063.0; Microsoft Edge 40.15063.674.0

**Additional context**
Tim has confirmed this bug:
 Ok cool think we isolated it. We added some code so tooltips work on long press. They maybe don’t need to add this case on windows. So log a bug and I think we can correct this.

**Comment by tmcconechy** [comment] 2018-12-14 20:14
Duplicate of #1354

**Closed by tmcconechy** 2018-12-14 20:14 UTC
Labels: [2], type: bug :bug:
