### ISSUE TITLE
Filter options not translated in ar-SA culture

### ISSUE THREAD

**Issue by pjm16** [infor-design/enterprise-ng#739] opened 2020-02-18 20:43 UTC
**Describe the bug**
The DataGrid filter options appear in English when the app is set using the ar-SA Arabic culture

**To Reproduce**
1. switch to Arabic culture - Soho.Locale.set('ar-SA');
2. Run any DataGrid screen uses filtering
3. Open up the filter options

**Expected behavior**
The filter options should be translated as well

**Version**
- ids-enterprise-ng: 6.2.0

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version latest

**Additional context**
screenshot reproduced in the Soho app
![Capture](https://user-images.githubusercontent.com/29760363/74776359-67827980-5265-11ea-9a0a-8804aad651b4.PNG)

**Comment by tmcconechy** [comment] 2020-02-18 20:47
Does ar-EG work ok? Because this works fine on EP on 4.23 https://4230-enterprise.demo.design.infor.com/components/datagrid/example-filter?locale=ar-SA

I think the issue might be that the "share" translations. So when you load ar-SA it will load ar-EG too and use that, maybe thats not working in the demo app.

**Comment by pjm16** [comment] 2020-02-19 12:33
hi @tmcconechy ar-EG does appear to have the same issue. I'm dropping "Soho.Locale.set('ar-EG')" into the constructor of the datagrid-dynamic.demo.ts - the grid is localized but the dropdown language remains as English.

**Comment by tmcconechy** [comment] 2020-02-19 14:23
You should set the locale earlier in the app start up https://github.com/infor-design/enterprise-ng/blob/master/docs/QUICKSTART.md#add-a-sohoxi-component that way you can ensure it is loaded as it is asynchronous. There is an example in the quick start app https://github.com/infor-design/enterprise-ng-quickstart/blob/master/src/app/app.component.ts#L13

Or you can use src/app/locale-initializer/locale-initializer.service.ts as an example like the sample app that pulls the locale from the browser. 

So i think your just setting it to close to the app init.

**Comment by pjm16** [comment] 2020-02-19 19:01
hi @tmcconechy this was just meant to be a quick illustration. ar-SA translations are not appearin. I can see ar-EG does load when it's bootrapped properly though it's not one of the languages Portal currently offer

**Comment by tmcconechy** [comment] 2020-02-19 19:04
I tried to bootstrap ar-SA properly and it did work. So when you properly boot strap it is it working?
The "trick" is that we only get arabic translations and we make add them to the ar-EG file. So when you switch to ar-SA it will also get ar-EG so it has the translations.

Nonetheless everything i test in the demo app is working. Can you reproduce any issue while everything is bootstrapped properly in the demo app?

**Comment by pjm16** [comment] 2020-02-19 19:55
hi Tim it's not a trick we can really use. IONAPI runs under Portal & it wouldn't be viable to add culture mappings. Hopefully it's an issue that can be addressed by the translations team?

Ideally we could split language from culture as there's really no direct correlation. I digress slightly, there's a wider issue for us is that Portal have already gone that way, so integrating our app with both Portal & Soho standards is challenging

**Comment by tmcconechy** [comment] 2020-02-19 20:08
I'm not really sure 100% what i can do. As i have no way to reproduce this on our end. If you give me one i could investigate it. But not seeing it here... Some questions that may help tho:

- Do you include IDS from npm? If so the locales should all be there and it should work like the demo app?
- Or do you just include ar-SA and not ar-EG? If so then i could see that would be the issue.
ar-SA https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/ar-SA.js 
ar-EG - https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/ar-EG.js
If this is the case can you copy the strings into your custom ar-SA file? Or just include ar-EG anyways? As a file even if you dont technically support it.
- We could copy the language to new files... Or would could copy the "same" language to all files but that would be a bit of a  change and duplication of code.

**Comment by tmcconechy** [comment] 2020-02-19 20:23
Ok, i reread this and i think i get it. Basically you cant do it any other way... I think one other idea i was toying with is making everything refresh dynamically when i language is changed.

If i put in this in src/app/datagrid/datagrid-dynamic.demo.ts
```
  constructor(
    private service: DataGridDemoService
  ) {
    Soho.Locale.set('ar-EG');
  }
```

I see what you are saying and its probably because the grid is initialized before that is done. is there anything in the NG lifecycle we can call that fires first before the component is initialized? @bthharper 

One other idea is to place the scripts directly in the `<head>` which could avoid the async issue.

**Comment by tmcconechy** [comment] 2020-02-19 20:29
Also (me again). I noticed that the src/app/datagrid/datagrid-settings.demo.ts example can be "made" to work.

- change src/app/datagrid/datagrid-settings.demo.ts
- edit the constructor to add the locale.set
```
  constructor(gridService: SohoDataGridService) {
    Soho.Locale.set('ar-SA');
    (gridService as DataGridDemoService).addColumn({
      id: 'rowReorder',
      name: '',
      field: 'id',
      align: 'center',
      sortable: false,
      formatter: Soho.Formatters.RowReorder,
      width: 80
    });
  }
```
- load the page 
- click make change

So some actions / settings cause a rerender. Maybe we can expose a rerender method as there is one in the datagrid. But this is not as good as finding a way to load the locale before the datagrid renders (that im unsure of).

**Comment by pjm16** [comment] 2020-02-19 21:25
Hi Tim I added the locale.set(‘ar-SA’) to the app.component constructor in the Soho app to rule out timing issues, & then went to a data grid & opened the filter options. I saw it working ok for Egypt but not SA. I was hoping translations could be added to the ar-SA file if that’s the issue. I can attach my test app tomorrow if helps?

**Comment by tmcconechy** [comment] 2020-02-19 21:29
Sure please attach so we are on the same page. I thought I saw it working for both when I tried on my end but will have a look at your example when you post and see.

**Comment by pjm16** [comment] 2020-02-20 13:15
[enterprise-ng.ar-SA.zip](https://github.com/infor-design/enterprise-ng/files/4230818/enterprise-ng.ar-SA.zip)
hi Tim, test app attached. I've added just 1 line in the app.component constructor to set the locale to ar-SA.

I updated the code this morning - it's an issue we're seeing in 6.2.0 & after taking the latest master branch it initially appeared ok.

However I noticed the filter options falling back to English after a while so I'm unclear if it's the same issue as 6.2.0.  However the translations are being dropped which doesnt seem right.

To reproduce
 - compile the app & run "ng serve"
- go to the dynamic grid & open a filter dropdown. You will see Arabic here (unclear if this was the case in 6.2.0 though, it's possible they were in English from the get-go)
- refresh the app - either refresh Chrome browser, or re-save a file in VS Code & the "ng serve" will refresh the app anyway
- open a new Grid screen & open a filter dropdown

On the last step you'll see the grid has maintained the ar-SA formatting, but the translations have been dropped & fallen back to English, in the filter dropdown at least.

In IONAPI I believe we're holding our own translations, but the SOHO translations are being cleared out

**Comment by tmcconechy** [comment] 2020-02-20 14:42
It appears in this case that the src/app/locale-initializer/locale-initializer.service.ts (Initializer service). Is also setting the locale back to en-US so there is a timing issue using both methods.

If you change line 44 of src/app/locale-initializer/locale-initializer.service.ts  to `await Soho.Locale.set('ar-SA').then(() => {` you can then see it working (hardcoded). Maybe this was all fixed by fixes since 6.20 as we did a lot of work on translate, in fact "separating" the language as https://github.com/infor-design/enterprise/blob/master/docs/CHANGELOG.md (See [Locale] changes there were many).

Also the quick start is updated to show using the initializer service https://github.com/infor-design/enterprise-ng-quickstart . But i think depending exactly what you do in IONAPI you maybe just need to update and call init on app load?

**Comment by bthharper** [comment] 2020-02-20 17:57
Adding any initialization within a component will potentially not work, as the load is asynchronous.  You really need to use the *APP_INITIALIZER* to ensure the locale is loaded before the application.  The other option is to use a lazy loaded route, however when I tried this I still had issues.

The `await` is definitely needed, to ensure the initializer does not complete until the locale's are loaded.

**Comment by tmcconechy** [comment] 2020-04-10 19:40
Support completed for now.

**Closed by tmcconechy** 2020-04-10 19:40 UTC
Labels: [2], type: bug :bug:, type: support :sos:
