### ISSUE TITLE
Dropdown: Pre-selects first value - Unable to star with nothing selected

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#630] opened 2019-10-02 11:39 UTC
**Describe the bug**
Dropdown automatically pre-selects 1st option

**To Reproduce**
1. Go to ids-enteprise-ng demo app
2. Click on dropdown-simple
3. use this html
```
          <select soho-dropdown
                  [noSearch]="true"
                  [multiple]="filterField.isMultiselect"
                  [closeOnSelect]="!filterField.isMultiselect"
                  (change)="onChange($event)">
            <option *ngFor="let option of filterField?.allowedValues" [value]="option">{{option}}</option>
          </select>
```
and this model
```
  filterField = {
    allowedValues: [1, 2, 3, 4, 5],
    isMultiselect: true
  };
```
4. See that 1st option is selected

**Expected behavior**
I expect no items selected unless ngModel or value attributes are used

**Version**
- ids-enterprise-ng: 6.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/66041319-e296fd80-e519-11e9-8740-e16e13fca8d2.png)

**Comment by tmcconechy** [comment] 2019-10-02 12:22
The problem is that this is the default for normal HTML select elements in that if non are selected the first element will always be selected.

We had a couple of ways to deal with this namely:
1. ../components/dropdown/test-blank-initially.html -> adding a blank item and selecting that or making it the first.
2. ../components/dropdown/example-placeholder.html -> using a place holder

It appears that 1. is not working. In addition i could see that from an Angular side dealing with this differently. But i think it would be a breaking change to not select the first element. If the blank item worked in this example i wouldnt be very concerned about this issue but since that is not i think we should investigate.

You might try mapping to a blank item if you need this meanwhile `&nbsp;` as maybe it works from an NG side.

**Comment by Fruko** [comment] 2019-10-02 12:37
I see, but what does not make sense to me is that 
```
          <select soho-dropdown soho-busyindicator noSearch name="states"
            (update)="onUpdated($event)"
            (change)="onChange($event)">
            <option *ngFor="let option of options" [value]="option.value">{{option.label}}</option>
          </select>
```
does not preselect it

**Comment by tmcconechy** [comment] 2019-10-02 12:43
OK i see its is it multiselect so that ngFor will just generate for example
```
        <option value="AL">Alabama</option>
        <option value="AK>Alaska</option>
        <option value="AZ">Arizona</option>
```

I think you will need to try and optionally set the `selected` attribute for multiselect but for dropdown it should select the first? May have to debug here but i think explicitly setting selected should work fine.

```
  <option *ngFor="let option of options" [selected]="option.isSelected" [value]="option.value">{{option.label}}</option>
```
?

**Comment by Fruko** [comment] 2019-10-02 12:48
I tried and even that pre-selects value so that's interesting because it looks like that pre-select of 1st option even ignores selected attribute

```
    <option *ngFor="let option of filterField.allowedValues"
            [selected]="false"
            [value]="option">{{option}}</option>
```

**Comment by tmcconechy** [comment] 2019-10-02 12:54
yeah `selected="false"` seems to be the same as just `selected` or `selected=true` so i think you need to either set selected or not ad it at all.

What is the use case here you want? Is it to have nothing selected initially at all?

**Comment by Fruko** [comment] 2019-10-02 12:59
yes, that is our use case, because we use it in filters and by default we keep the filters empty unless users change it

**Comment by tmcconechy** [comment] 2019-10-02 13:04
Yeah this needs further investigation.

**Comment by tmcconechy** [comment] 2019-10-02 13:11
Was looking at something else and happened on this...As a possible suggestion

```
            <select id="company-name" name="company-name" class="dropdown">
              <option value="">None</option>
              <option value="jawbone">Jawbone, Inc.</option>
              <option value="infor">Infor</option>
            </select>
```

**Comment by tmcconechy** [comment] 2020-03-26 14:13
Given that this is consistent with the way select elements work, i cant see any changes i can apply. Closing for now unless you have a further suggestion?

**Closed by tmcconechy** 2020-03-26 14:13 UTC
Labels: [3], type: bug :bug:
