### ISSUE TITLE
Radio Button Component: Clicking first radio button triggers the last radio button

### ISSUE THREAD

**Issue by saramartininfor** [infor-design/enterprise-ng#455] opened 2019-04-29 12:51 UTC
**When selecting the first radio button, the last radio button is being selected**
When having a list of horizontal radio buttons and selecting the first radio button, the last radio button is selected instead. This happens only when clicking the center of the radio button. Clicking the label works fine. See attached gif for scenario. This issue is encountered here: https://design.infor.com/code/ids-enterprise/latest/demo/components/radios/example-horizontal

**To Reproduce**
1. Create a list of horizontal radio buttons with label for each one
2. Click on the first radio button to select it (option one in link above)
3. Actual behavior: the radio button with label Option four is selected

**Expected behavior**
Radio Button with label Option one is selected.

**Version**
- ids-enterprise-ng: v5.2.1
- ids-enterprise: v4.17.1

**Screenshots**
![radio-button-option-select](https://user-images.githubusercontent.com/50106355/56897188-2038bb80-6a8e-11e9-8252-c23c7c5d7ce4.gif)

**Platform**
 - OS Version: MacOS Mojave
 - Browser Name: Chrome
 - Browser Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2019-04-29 12:55
This is a duplicate of https://github.com/infor-design/enterprise/issues/1878 which has already been fixed in the next version 4.18 available soon.

**Closed by tmcconechy** 2019-04-29 12:55 UTC
Labels: status: duplicate
