### ISSUE TITLE
Broken accordion - 6.3.0

### ISSUE THREAD

**Issue by James-Carlin** [infor-design/enterprise-ng#707] opened 2020-01-16 09:47 UTC
**Describe the bug**
The accordion panels are expanded by default and cannot be collapsed.

**To Reproduce**
1. Go to enterprise-ng demo
2. Click on accordion
3. See error

**Expected behavior**
Accordion panels should be collapsed based on configuration and expand/collapse should work.

**Version**
- ids-enterprise-ng: [v6.3.0]

**Comment by tmcconechy** [comment] 2020-01-16 10:32
Duplicate of https://github.com/infor-design/enterprise-ng/issues/701

**Comment by tmcconechy** [comment] 2020-01-16 10:33
This was found and fixed in 4.25/6.4 (4.25 now has a beta but 6.4 beta will be Friday).

**Comment by tmcconechy** [comment] 2020-01-17 12:42
marking as it was fixed on #701

**Closed by tmcconechy** 2020-01-17 12:42 UTC
Labels: status: duplicate, type: bug :bug:
