### ISSUE TITLE
DataGrid: Render issue with single column within modal dialog

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#418] opened 2019-04-08 21:26 UTC
Describe the bug
When a single column datagrid is within a modal dialog, the datagrid has render issues.  The column header does not extend across the datagrid. 

1. Changed the file datagrid-demo.service.ts  to have a datagrid with a single column (see attached file)
2. Open the existing example datagrid-lookup-click-function
3. Click on a cell within the Lookup Click column
4. Click on the lookup icon

Expected behavior
Within the modal dialog the column header for the last column should span across

Is related to https://github.com/infor-design/enterprise/issues/1818.

**Comment by claudenbach** [comment] 2019-04-08 21:31
[GitNg-418.zip](https://github.com/infor-design/enterprise-ng/files/3056310/GitNg-418.zip)

**Comment by claudenbach** [comment] 2019-04-08 21:32
![image](https://user-images.githubusercontent.com/39804038/55758280-e68b0c80-5a1b-11e9-9340-e11a058bce81.png)

**Comment by tmcconechy** [comment] 2019-04-08 21:54
Would this be the identical issue to https://github.com/infor-design/enterprise/issues/1923 ?

**Comment by claudenbach** [comment] 2019-04-23 15:58
We are also seeing this issue on datagrids that contain more than one column.  Its always the last visible column were the column header does not extend across the entire space.  Sometimes this happens when the list is first rendered, sometimes it happens when the user pages, sorts or filters the list.

**Comment by tmcconechy** [comment] 2019-07-29 13:21
@claudenbach Im unable to reproduce this issue. I:
- copied datagrid-demo.serice.ts over the existing one on NG master
- when to http://localhost:4200/ids-enterprise-ng-demo/datagrid-lookup-click-function
- clicked the lookup column
- the example looked nothing like the screen shots

Also did https://github.com/infor-design/enterprise/issues/1923 solve the issue?

**Comment by tmcconechy** [comment] 2019-08-07 19:16
Was not able to reproduce this issue so closing

**Closed by tmcconechy** 2019-08-07 19:16 UTC
Labels: [2], focus: datagrid, status: cant reproduce, status: on hold :pause_button:, team: landmark, type: bug :bug:
