### ISSUE TITLE
Icons are not appearing in iOS version 12.1 below

### ISSUE THREAD

**Issue by joshuatorreinfor** [infor-design/enterprise-ng#1206] opened 2022-01-04 03:15 UTC
**Describe the bug**
All icons are not shown in browser pages and is happening on both Chrome and Safari (Browserstack).

The issue is reproducible in versions iOS 12.1, iOS 11 and below.

This could either be an issue with Browserstack or iOS 12.1 but versions above iOS 12.4 is showing the icons properly.

I have tried rendering SVG with image links and manually drawing SVG icons and seems to work properly. 

However, SVG using `<use href> `is not displaying.  But using` <use xlink:href>` will properly display the images.

**To Reproduce**
1. Go to Browserstack and select a device with version iOS 12.1 or below
2. Go to any of the following sites:
https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-legend
https://design.infor.com/code/ids-enterprise/latest/demo/components/alerts/example-index?theme=uplift&variant=light
https://design.infor.com/code/ids-enterprise/latest/demo/components/button/example-index?theme=uplift&variant=light

3. See that the icons are missing and not displayed

**Expected behavior**
The icons should properly render and displayed

**Version**
- version deployed in the demo in the links above

**Platform**
 - Browserstack Device (iPhone 8, iOS 12.1, 11, and iOS 13 (working))

**Additional context**
I have only tried in Browserstack and not in an actual device. Issue is only reproducible in iOS 12.1 and below

**Screenshots**
**MISSING ICONS (iOS 12.1 iPhone 8)**
**Alerts**
![Alerts-IDS-iPhone8-v12 1](https://user-images.githubusercontent.com/97070314/148004664-77ff7f76-8d11-4bf6-a0bc-fa71e15d8059.PNG)
**Buttons**
![Button2-IDS-iPhone8-v12 1](https://user-images.githubusercontent.com/97070314/148004665-e33fc956-00f7-4374-93d7-09ada307b811.PNG)
![Button1-IDS-iPhone8-v12 1](https://user-images.githubusercontent.com/97070314/148004666-3af5d337-33c0-4c69-bccc-8fe7ab12c5a9.PNG)
**Week View**
![WeekView-IDS-iPhone8-v12 1](https://user-images.githubusercontent.com/97070314/148004667-912930b7-bee5-483b-9808-1ba45bf18ba7.PNG)
**Date Picker**
![DatePicker-IDS-iPhone8-v12 1](https://user-images.githubusercontent.com/97070314/148004668-2270c456-cfad-4d18-8f54-3fd5fc1c0ff0.PNG)

**EXPECTED ICONS  (iOS 13.2 iPhone 8)**
**Alerts**
![Alerts-IDS-iPhone8-v13 2](https://user-images.githubusercontent.com/97070314/148004674-8ad15aba-2714-4875-914c-355761158fe2.PNG)
**Buttons**
![Button1-IDS-iPhone8-v13 2](https://user-images.githubusercontent.com/97070314/148004671-44fde3e0-b62e-4170-a4b8-f0e4305f66fc.PNG)
![Button2-IDS-iPhone8-v13 2](https://user-images.githubusercontent.com/97070314/148004672-4ecd7887-7f87-4b11-aa32-6419e45494cc.PNG)
**Week View**
![WeekView-IDS-iPhone8-v13 2](https://user-images.githubusercontent.com/97070314/148004659-521ba364-9c6e-4a74-907c-f256b39c1b95.PNG)
**Date Picker**
![DatePicker-IDS-iPhone8-v13 2](https://user-images.githubusercontent.com/97070314/148004662-bfef0a47-a9b6-4b4d-932d-c995b012b1de.PNG)

**Comment by tmcconechy** [comment] 2022-01-04 14:33
@joshuatorreinfor this is a duplicate of 
https://github.com/infor-design/enterprise/issues/3637
https://github.com/infor-design/enterprise/issues/3964
https://github.com/infor-design/enterprise/issues/4147

It is a bug in safari and cannot be fixed by us. If still on IOS 12 you would need to upgrade to IOS 12.1
Additionally we only now support R-1 browsers so technically we only support IOS 13 - 15 now anyways

**Closed by tmcconechy** 2022-01-04 14:33 UTC
Labels: status: wont fix :no_entry_sign:, type: bug :bug:, [2], status: duplicate
