### ISSUE TITLE
Lookup: dataset view doesn't set back to its initial view after filter clear

### ISSUE THREAD

**Issue by helloimYS** [infor-design/enterprise-ng#790] opened 2020-04-15 05:09 UTC
**Describe the bug**
When using the lookup component with filter header, when entered some value in filter and select on a data/close the lookup (without clearing the value in filter header), and re-open the lookup, the value in filter is clear however the datagrid view doesn't set back to its initial view (same as the view without applying filter).

**To Reproduce**
1. Unzip the folder below, navigate into the project folder and run `npm install` to install all dependency and run `odin serve` to start the project.
[Testing-master.zip](https://github.com/infor-design/enterprise-ng/files/4479218/Testing-master.zip)
2. Open the lookup and enter '2' on id filter header
![image](https://user-images.githubusercontent.com/63391710/79298140-d05b3a80-7f12-11ea-834d-458af5691918.png)
3. Close the lookup without clearing the '2' on id filter header
![image](https://user-images.githubusercontent.com/63391710/79298288-5081a000-7f13-11ea-885e-5c9e1d357c9f.png)
4. Open the lookup again and see the '2' on filter header is cleared however the datagrid view doesn't reset to its initial view. 
![image](https://user-images.githubusercontent.com/63391710/79298316-61321600-7f13-11ea-9c24-ed62b065c981.png)

**Expected behavior**
- The datagrid view should be set back to its initial view. 
(Filter should be clear as well as datagrid view should be reset to its initial view)
- To achieve the same behavior like product field in [here](https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-filter-row)

**Version**
- ids-enterprise-ng: v5.0.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 80.0.3987.163 (Official Build) (64-bit)

**Additional context**
- The input field might not be shown on first launch, try to refresh the browser until the input field is show on screen.

**Comment by tmcconechy** [comment] 2020-04-15 14:28
This is a duplicate of https://github.com/infor-design/enterprise/issues/2566 and https://github.com/infor-design/enterprise/issues/2568 which have been solved on 4.20 or later.

The exact commit is here https://github.com/infor-design/enterprise/pull/2572

**Closed by tmcconechy** 2020-04-15 14:28 UTC
Labels: [2], status: duplicate, type: bug :bug:
