### ISSUE TITLE
Tooltip: <soho-tooltip> "title" attribute conflicts with <span>"title" attribute

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#925] opened 2020-10-15 11:32 UTC
**Describe the bug**
`title` attribute in `soho-tooltip` is used to give tooltip a header. `title` attribute in `span` is used to give span a native tooltip.
When used together in e.g. `<span soho-tooltip title="Hello World">` I will get two tooltips.

**To Reproduce**
1. How to in description

**Expected behavior**
span should only display `soho-tooltip`

**Screenshots**
![image](https://user-images.githubusercontent.com/542598/96117714-cb3f6e00-0eea-11eb-92c1-cc65b20fbe71.png)

**Comment by tmcconechy** [comment] 2020-10-15 13:43
Cant seem to reproduce this. I put this code in src/app/tooltip/tooltip.demo.html and run the page and i just get one tooltip. Do you want to try the latest 8.0 or 7.7?

```
<span soho-tooltip title="Hello World">this is a span</span>
```

<img width="270" alt="Screen Shot 2020-10-15 at 9 42 55 AM" src="https://user-images.githubusercontent.com/814283/96137681-ed28f880-0eca-11eb-834c-645ff88bd803.png">

**Comment by guoliang** [comment] 2020-10-16 15:27
I was on version 7.6.2, and changed to 8.0 to try. It was the same issue. How is the native tooltip removed? I figure out IDS going to remove the `title` attribute somehow?

**Comment by tmcconechy** [comment] 2020-10-16 17:37
OK, can you reproduce in our demo app? I tried this again and tried on both windows and mac just to be sure. And if i just 
```
<span soho-tooltip title="Hello World">this is a span</span>
```
to src/app/tooltip/tooltip.demo.html it works fine, and im not getting the browser tooltip at all. What should happen is when the component invokes it removes that attribute and stores it internally. Must be something on what your doing specifically?

**Comment by tmcconechy** [comment] 2020-12-30 14:22
Closing due to not able to reproduce

**Closed by tmcconechy** 2020-12-30 14:22 UTC
Labels: [3], status: cant reproduce, type: bug :bug:
