### ISSUE TITLE
SOHO-7467: Ng Lookup Control - ability to pass buttons collection

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#82] opened 2018-05-31 20:00 UTC
We need to ability to pass the buttons collection to the lookup control in angular.
At the moment this property is not exposed.
Reason for this: we need to translate the labels.
This is available in jquery controls

**Comment by tmcconechy** [comment] 2020-02-19 19:12
Seems to be a duplicate of #467

**Closed by tmcconechy** 2020-02-19 19:12 UTC
Labels: [3], type: bug :bug:
