### ISSUE TITLE
Datagrid: Font color difficult to read with TargetedAchievement formatter

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#601] opened 2019-09-04 21:07 UTC
Describe the bug
Getting push back that the font color is difficult to read and that the color itself is inconsistent when using the TargetedAchievement formatter.

To Reproduce
1. Using the attached test-targeted-achievement.html
2. Note the font color of the progress bar text for the Tomac row
3. Note the font color of the progress bar text for the Turner Bikes row
4. Change to the Uplift theme and note
5. Change to the Variant of Light, Dark, High Contrast

Expected behavior
Font color of the text on the progress bar should be consistent and easy to read.  

Testing with the various themes:
- Vibrant - Light => font is black, if value > 75 font changes to white
- Subtle - Light => font is black; if value > 75 font changed to white
- Subtle - Dark => font is always white
- Subtle - Contrast => font is always white

Comparing to forms, the font color change occurs when the value is > 55.  So the list and form as inconsistent.

**Comment by tmcconechy** [comment] 2019-09-04 21:11
The problem is it cant be both consistent and easy to read over the background. So we have to pick one color white or black and always show that for all of them, from what your saying. Depending on if the use a lighter color it may not look great.

This color may not always work depending on the color of the background. One option is to make it all white?

![Screen Shot 2019-09-04 at 5 10 46 PM](https://user-images.githubusercontent.com/814283/64291791-fa895a80-cf36-11e9-9fad-7b2cad49a373.png)

**Comment by tmcconechy** [comment] 2019-09-04 21:13
Duplicate of https://github.com/infor-design/enterprise/issues/2730

**Closed by tmcconechy** 2019-09-04 21:13 UTC
Labels: [3], team: landmark, type: bug :bug:
