### ISSUE TITLE
Button is disabled inside expandable area while in modal dialog

### ISSUE THREAD

**Issue by James-Carlin** [infor-design/enterprise-ng#1247] opened 2022-03-02 13:14 UTC
**Describe the bug**
Standard soho button is disabled inside expandable area when it is inside a modal dialog

**To Reproduce**
1. open modal-dialog-datagrid.component.html in enterprise-ng demo app
2. paste the following div below datagrid code: 

```
<div>
  <soho-expandable-area class="scrollable-flex-header">
    <soho-expandable-pane>
      <p>
        Ubiquitous out-of-the-box, scalable; communities disintermediate beta-test, enable utilize markets dynamic infomediaries virtual data-driven synergistic aggregate infrastructures, "cross-platform, feeds bleeding-edge tagclouds." Platforms extend interactive B2C benchmark proactive, embrace e-markets, transition generate peer-to-peer.
        Capitalise on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.
      </p>
      <div>
        <button soho-button="secondary">
          Disabled Test
        </button>
      </div>
    </soho-expandable-pane>
    <soho-expandable-footer>
      <button soho-button="tertiary" [expandableExpander]="'true'">
        <span>Show Stuff</span>
      </button>
    </soho-expandable-footer>
  </soho-expandable-area>
</div>
```
3. Observe by clicking 'Dialog With Datagrid' button and expanding the panel.

**Expected behavior**
Button should be enabled.

**Version**
- ids-enterprise-ng: latest version

**Comment by tmcconechy** [comment] 2022-03-02 15:00
I tried to reproduce this on latest 13.2.0-dev and cannot. I think this was a duplicate of https://github.com/infor-design/enterprise-ng/issues/1210 and I think we patched it already

Can you try [13.1.1](https://www.npmjs.com/package/ids-enterprise-ng/v/13.1.1) and confirm?

**Closed by tmcconechy** 2022-03-02 15:00 UTC
Labels: type: bug :bug:, [2], status: duplicate
