### ISSUE TITLE
Row selection is lost with a standalone pager

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#446] opened 2019-04-23 15:17 UTC
**Describe the bug**

When using a standalone pager (`soho-standalone-pager`) selections are not retained when navigating between pages.

Setting `allowSelectAcrossPages` to true does not work (and is also not exposed as an Input) as this only works if the `source` and `pager` members are set in the data grid.

**To Reproduce**

Using the `datagrid-standalone-pager` example, modify the code to clone the data emulating data being passed back from a server (which does not contain the selected state).

```typescript
  const cloned = this.data.map(x => Object.assign({}, x));

  const result: any = {
    data: cloned.slice(this.beginIndex, this.endIndex),
    firstPage: this.beginIndex === 0,
    lastPage: this.endIndex >= this.data.length - 1
  };
```

```sh
npm run build:lib
npm run start
```

Navigate to http://localhost:4200/ids-enterprise-ng-demo/datagrid-standalone-pager.

Select rows and move forward and back.

**Expected behavior**

When moving between pagers, it should be possible to get the datagrid to keep any selections as if the pager was created by the datagrid itself.

**Version**
- ids-enterprise-ng: 5.2

**Screenshots**
N/A

**Platform**
All

**Additional context**

**Comment by bthharper** [comment] 2019-04-24 15:57
@tmcconechy  - not sure if this is more a bug for the ep controls, as the logic for syncing the selection is there.

**Comment by tmcconechy** [comment] 2019-04-24 15:59
@bthharper It seems ok to me on the EP example though? http://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-multiselect-select-across-page.html Does it not?

Also the input would be here. Im guessing the problem is that you clone. I think i'm holding the references.

**Comment by bthharper** [comment] 2019-04-24 18:35
@tmcconechy - looking at the EP code, the sync selected methods are not called when the pager is not set (and possibly some other state too), and in the case of a standalone pager these are not set.

I added the clone to emulate a real backend services returning pages, where as the demo just keeps a list in memory and returns slices of it.  This isn't something you get when using a backend.  

Can we expose the "sync function" ?

**Comment by tmcconechy** [comment] 2019-04-24 18:38
OK, makes sense. I think we could expose syncSelectedRows, but might be better to put it in the callback function or loadRows so it gets called during paging? Are you saying you could reproduce it in EP only?

**Comment by bthharper** [comment] 2019-04-30 18:09
I've not tried it in EP only, but it's not an issue with NG really, more a case the standalone pager does not integrate with the datagrid in the same was as an embedded one.

We call `loadData` like this when the input data changes:

```typescript
@Input() set data(data: any[]) {
    this.gridData = data;
    if (data && this.jQueryElement) {

      this.ngZone.runOutsideAngular(() => {
        // @todo add hints for this too, as other changes may force a rebuild?
        this.datagrid.loadData(data);
      });
    }
  }
```

**Comment by bthharper** [comment] 2019-10-18 13:23
@tmcconechy  - we've rolled our own code to keep selections whilst paging, however we need some tighter integration with the datagrid to allow the selection checkbox to be interacted with, that is:

* an event when the item is clicked.
* the ability to set the state to 'partial'

Thoughts?

**Comment by tmcconechy** [comment] 2019-10-18 13:33
- the selected event (second arg) can help with the clicked.
- to set the state it is a class. we would need to move this into a public function https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6983-L6995

**Comment by bthharper** [comment] 2019-10-18 13:50
I'll add the 'type' argument into the datagrid component, that will help.

```typescript
interface SohoDataGridSelectedEvent {
  e: JQuery.TriggeredEvent;
  rows: SohoDataGridSelectedRow[];

  /** What was the action that caused the event? */
  type: SohoDataGridSelectedEventType;
}
```

**Comment by bthharper** [comment] 2019-10-18 13:54
I might look to add a method to set the selection state - we can always change it to use the correct api later.

**Comment by tmcconechy** [comment] 2019-10-18 13:56
Sure it should be fairly straightforward to move that code https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6983-L6995 to a method fx `setHeaderCheckboxState` or something

**Comment by bthharper** [comment] 2019-10-21 07:50
@tmcconechy - unfortunately the change does not quite work as I hoped.  The problem is that the (selected) event is fired on paging (we call `loadData`) - with the extra argument of 'deselectall'.  In our event handler I cannot determine if the source of the event was a call to `loadData` or the user clicking on the deselect all checkbox.

Looking at the code, this is because there is no `pagerinfo` on the datagrid.

**Comment by tmcconechy** [comment] 2019-10-21 13:20
Ok whats your suggestion then? Do we need to look at this in the next sprint again?
Also to play the devils advocate here, why cant we just use the paging feature in the normal way which works ok? I.E. Curious whats driving the need to make it seperate?

Also maybe @pwpatton has some suggestions as I did do the standalone pager as requested by their team so I assume this is all working for them.

**Comment by bthharper** [comment] 2019-10-21 13:25
Nothing wrong with playing devil's advocate.  We use a state model to hold the current selection/page/row so we can drive the data grid using `@Inputs` rather than a source function.

This allows us to use the same state model in different views and also to decouple the model view and controller aspects.  

It's close to working, if we could tell the data grid paging is being handled by the client (using a standalone pager) that may help.

**Comment by pwpatton** [comment] 2019-10-21 13:28
@bthharper agreed, sometimes the pagerInfo has gotten in the way with this technique. It would be nice to be able to completely remove it as a consideration in the datagrid with some option: 
```
gridOptions.noPaging = true;
```

**Comment by tmcconechy** [comment] 2019-10-21 13:29
OK could you put together something i could look at? Im not 100% sure if i follow the last issue.
But as per @pwpatton we have `paging: false` ? That means dont consider a paging is involved.

**Comment by pwpatton** [comment] 2019-10-21 13:30
@tmcconechy Yes, we could make a nice sample in ids-ng. It's a super simple technique.

**Comment by bthharper** [comment] 2019-10-21 13:44
Yep - the problem I have is that the datagrid fires `selected([], 'deselectall')` when calling `loadData` if the `pagerInfo` member variable is undefined.  

This means I can't detect the user pressing header selection box using that second argument as we first thought, as paging deselects all the rows.

If we could tell the `datagrid` the rows are being paged by the client perhaps?

I'll try and knock together an example,  using the existing standalone paging example.

**Comment by pwpatton** [comment] 2019-10-21 14:05
We have this issue also and got around it somehow. (don't remember how).

**Comment by bthharper** [comment] 2019-10-21 14:22
I did think of inspecting the event, but this just seems too brittle.

**Comment by tmcconechy** [comment] 2019-10-21 14:24
I'll have a look at your example and see about it.

**Comment by bthharper** [comment] 2020-02-21 16:26
I've worked around this in our code by keeping track of selected rows.

**Comment by tmcconechy** [comment] 2020-02-21 16:29
We have a datagrid option selectRowsAcrossPages that will do that for serverside paging. This may also help as it keeps track. But i didn't try it with standalone pager.

https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-multiselect-select-across-page.html

**Comment by tmcconechy** [comment] 2020-12-30 14:26
Closing this for now - but working this into the web component version. The pager will be just a dumb component with events.

**Closed by tmcconechy** 2020-12-30 14:26 UTC
Labels: [5], type: bug :bug:
