### ISSUE TITLE
soho-datepicker changes PM to AM when clicking "Today"

### ISSUE THREAD

**Issue by HPiresInfor** [infor-design/enterprise-ng#238] opened 2018-10-25 13:24 UTC
**Describe the bug**
When selecting date time, and setting PM. Clicking "Today" changes PM to AM

**To Reproduce**
1. Go to timepicker example 
2. Click on calendar
3. Change AM to PM
4. Click Today
5. Observe PM changes back to AM

**Expected behavior**
Time selection is maintained OR set to current time OR set to midnight current day

**Platform**
 - Any browser

**Comment by tmcconechy** [comment] 2018-10-25 13:28
This is a duplicate of https://github.com/infor-design/enterprise/issues/1087 so closing.
We plan on making today insert the current time or midnight depending on if useCurrentTime is set or not.

**Closed by tmcconechy** 2018-10-25 13:28 UTC
