### ISSUE TITLE
PopupMenuItem: clicking on disabled option throws error in console

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#482] opened 2019-05-15 09:38 UTC
**Describe the bug**
When clicking on a disabled option in `SohoPopupMenuItemComponent`, there is an error throwing in the console.

**To Reproduce**
1. Go to `popupmenu.demo.html` in example app.
2. Add `[isDisabled]="true"` to one of the `soho-popupmenu-item`.
3. Run the example app, open dev console (Chrome for example) and click on that disabled option

**Expected behavior**
There shouldn't be any errors.

**Version**
- ids-enterprise-ng: master branch

**Screenshots**
![image](https://user-images.githubusercontent.com/27772165/57765428-b95e0800-7705-11e9-8421-132a173d5fc5.png)

**Platform**
 - Device (if applicable) **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.157 (Official Build) (64-bit)

**Additional context**
Maybe disabled option should have prevent click or something.

**Comment by tmcconechy** [comment] 2019-05-15 15:36
I tried this on the latest master and could not reproduce. I think this was recently fixed by this issue https://github.com/infor-design/enterprise/pull/2113

**Closed by tmcconechy** 2019-05-15 15:36 UTC
