### ISSUE TITLE
CodeBlock: request a function to control whether tab key advances to next cell  

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#355] opened 2019-02-11 19:32 UTC
Datagrid column contains a CodeBlockFormatter and a CodeBlockEditor.  The grid has the options of cellNavigation set to true.  

When the user in the cell containing the CodeBlockEditor, this cell may contain multiple input elements.  When the user hits the tab key (or the shift+tab key) would like to control whether focus moves to the next cell.

In 3.5 version of the controls, there was a function on an editor stayInEditMode that was called for the editor to determine whether focus should move to the next cell.

Requesting something similar for 4.0.

**Additional context**
[CodeBlockEditor.zip](https://github.com/infor-design/enterprise-ng/files/2852732/CodeBlockEditor.zip)

![stayineditmode](https://user-images.githubusercontent.com/39804038/52588060-345f0c00-2e01-11e9-8ca6-8c2f789bda88.gif)

**Comment by tmcconechy** [comment] 2019-02-11 19:33
Is someone on your team picking up these code block issues? As they should be just on your side.
But if you need a setting to be worked in perhaps we can help with that.

**Comment by claudenbach** [comment] 2019-02-11 19:35
Would need something to control whether the focus moves to the next cell.

**Comment by tmcconechy** [comment] 2019-02-13 19:44
Other Ideas/Notes
- a tab event where you can do something and return false to prevent default or
- simply in the datagrid tab code check if anymore inputs in the field and change the logic to focus those
- Something similar here http://master-enterprise.demo.design.infor.com/examples/saleshub/product-search.html called inline editors. But they "stick out" of the cell all the time and only one in the cell

**Comment by lipetzan** [comment] 2019-03-19 17:57
Did this make the next sprint plan @clepore and @tmcconechy ?

**Comment by tmcconechy** [comment] 2019-03-19 18:11
@lipetzan - Yes, starting on this next actually

**Comment by clepore** [comment] 2019-03-19 18:21
@lipetzan Just an fyi, if you look under the right side bar for an issue, you can see what projects its in so you can see when we have it scheduled. We use projects to define the timeline and issues for our sprints and the names are like  "Enterprise 4.18.x (April 2019) Sprint".

You can also filter the issues on the repo's issue page to filter for projects and milestones (aka `is:open is:issue project:infor-design/45 milestone:Landmark`...or use the dropdowns) to give you a nice overview of issues per project 👍

**Comment by lipetzan** [comment] 2019-03-19 18:32
Thanks Chris. So this has not been scheduled then right?  When we prioritized the enterprise list for your sprint planning I think we all forgot about the enterprise-ng pile as well.  two piles :(

**Comment by tmcconechy** [comment] 2019-03-19 19:17
I think that the issue is the projects are currently marked as private so you cannot seem them on the issue (also check you are logged in). But this is scheduled and we did look at some NG issues. 

Im doing this one right now and will reach out to @claudenbach with some questions.

**Closed** 2019-04-17 20:51 UTC
Labels: [3], priority: high, type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2019-04-19 16:52
This issue is now resolved.
