### ISSUE TITLE
Locale: Soho.Locale.setLanguage not working for "nb-NO" Norwegian language 4.31.0 and 4.31.1 library

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#874] opened 2020-07-24 13:08 UTC
**Describe the bug**
Soho.Locale.setLanguage('nb-NO') function not working with "nb-NO"  Norwegian language.

**To Reproduce**
1. Go to 'Dyanamic datagrid example in enterprise-ng and set language to it by using below function 
constructor(
    private service: DataGridDemoService
    
  ) {

    Soho.Locale.setLanguage('nb-NO').done(function () {
     Soho.Locale.translate('AboutText');
   });
  } '
2. save the changes and check in the browser.
3. When inspect in console we get error - "ERROR RangeError: Maximum call stack size exceeded" 

**Expected behavior**
Same function is working or other languages we expect it should work for "nb-NO" Norwegian language also.

**Version**
- ids-enterprise-ng: [v4.29.3]

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/42198413/88394166-908ed380-cddc-11ea-82b5-f57b738a0793.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/42198413/88394242-b6b47380-cddc-11ea-9b38-9c900a9f16c0.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
For 'nb-NO' language translation file resource are not translated for all text. We are using 4.29.3 Soho library. Please check below link.

https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/nb-NO.js

**Comment by tmcconechy** [comment] 2020-07-24 13:18
I think this is a duplicate of https://github.com/infor-design/enterprise/issues/3455

At any rate https://master-enterprise.demo.design.infor.com/components/datagrid/example-index and type `Locale.set('nb-NO')` in the console now works in the current version 4.30

In addition nb-NO shares translations with no-NO so they are all there  https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/no-NO.js#L61

Test Page:
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index?locale=nb-NO

We recently 4.31-dev got a few more updates to this file.

**Comment by dhumalkishor** [comment] 2020-08-24 10:31
Hi Tim,

This issue is not fixed. We are getting same error with 4.31.0 and 4.31.1 soho library.  Please review this issue.

**Comment by tmcconechy** [comment] 2020-08-24 13:17
ok, going to reopen. but the issue doesnt seem to happen in the normal components. I just see it when i modify the constructor in Angular. This is maybe not the best place to do it? I wonder if it works in the app.component instead using the Locale initializer see quick start

https://github.com/infor-design/enterprise-ng-quickstart/blob/master/src/app/locale/soho-locale-initializer.service.ts#L39

You can test this out and let me know or i'll get to this next sprint.

**Comment by dhumalkishor** [comment] 2020-08-25 13:05
We tried above solution but it didn't worked.

**Comment by tmcconechy** [comment] 2020-08-25 13:06
What do you mean by didnt work? And what did the code look like?

**Comment by tmcconechy** [comment] 2020-08-25 13:12
Actually you should also try passing only the language code to setLanguage.

```
Soho.Locale.setLanguage('no').done(function () {
 Soho.Locale.translate('AboutText');
```

**Comment by dhumalkishor** [comment] 2020-08-25 13:14
We have scenario where user can set browser language different and Local different. lets say we have set browser language to "ng-NO" and local is "en-US" . In this scenario we are expecting  application should be shown in "nb-NO" language expect Date control and Time control, when we change code as per your suggestion then it showing application in "nb-NO"  along with Date and Time control.

**Comment by dhumalkishor** [comment] 2020-08-25 13:15
We are passing language "nb-NO".

**Comment by tmcconechy** [comment] 2020-08-25 13:17
Ok, that's not expected. We only tested the language not the locale for this function https://github.com/infor-design/enterprise/blob/master/test/components/locale/locale.func-spec.js#L1474

So try:
```
Soho.Locale.set('no')
Soho.Locale.set('nb')

//OR if actually intended:
Soho.Locale.set('nb-NO')
```

FYI nb-NO maps to no-NO so they are the same data and file. So also as a workaround you can try that if it works (but it should work as above)

**Comment by bthharper** [comment] 2020-08-25 13:30
@tmcconechy - setting the locale should be done in an APP_INITIALIZER, see locale-initializer in the demo, otherwise the language resources and scripts are not loaded correctly. 

I just tried using *nb-NO* and *no-NO* in the demo by changing the *locale-initializer.module* and this "seemed" to work.

**Comment by tmcconechy** [comment] 2020-08-25 13:33
@bthharper yes thats what i said (I think). But the issue here i think is setting the language to a locale i.e.

```
setLanguage('nb')
vs
setLanguage('nb-NO')
```

**Comment by bthharper** [comment] 2020-08-25 13:41
@tmcconechy  - okay should have read it all properly.  When I try `nb` I get ...

![image](https://user-images.githubusercontent.com/8340092/91181663-1d30f800-e6e1-11ea-8c12-82a2eac06c6f.png)

**Comment by tmcconechy** [comment] 2020-08-25 13:43
Yeah. That works - but for some reason passing the full locale to setLanguage('nb-NO') is causing a stack loop. But technically its not supported. So not sure if its worth fixing (and probably no rush since its not correct)

**Comment by bthharper** [comment] 2020-08-25 13:47
So it's just `setLanguage` that has an issue.  The initializer code always calls `setLocale`.

**Closed** 2020-09-15 14:11 UTC
Labels: [2], type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2020-09-22 19:51
This issue is now resolved.
