### ISSUE TITLE
Editable Datagrid: Unable to use spaces

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-ng#1376] opened 2022-09-15 12:02 UTC
**Describe the bug**

**To Reproduce**
1. Git clone https://github.com/infor-design/enterprise-ng.git
2. Change branch to 14.1.x
3. npm install
4. npm start
5. open http://localhost:4200/ids-enterprise-ng-demo/datagrid-angular-editor
6. Click on row 1, Status cell
7. Type "On Hold"
8. Issue: Not able to add space 

**Expected behavior**
Should be able to add space and have value "On Hold" not "OnHold"

**Version**
- ids-enterprise-ng: 14.1.x 

**Screenshots**
![image](https://user-images.githubusercontent.com/53523076/190397570-660122dd-94c3-4697-a6af-7cca76193220.png)

**Platform**
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome
 - Browser Version: 105.0.5195.102 (Official Build) (64-bit)

**Additional context**
Space is also not working on Soho.Editors.Input.
Seen on Homepages where version ids-enterprise-ng: 14.1.x  is used

**Comment by tmcconechy** [comment] 2022-09-15 13:26
This is a duplicate of https://github.com/infor-design/enterprise/issues/6756 and has been fixed in 4.67/14.3.0

**Closed** 2022-09-16 13:42 UTC
Labels: type: bug :bug:, [1], status: duplicate
