### ISSUE TITLE
Lookup: In multiselect we are getting array of string instead of array of object

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#986] opened 2021-02-09 13:48 UTC
**Describe the bug**
In lookup control  we are getting array of string instead of array of object when we select more than 6 records.

We have forked and made our changes in https://github.com/JangleShubham/enterprise-ng
Please install this project and run it and go to the path http://localhost:4200/ids-enterprise-ng-demo/lookup.

**To Reproduce**
1. Go to 'Open lookup multiselect under label "Products (Async Results) Multi Select"'
2. Popup with grid will get open, apply for filter and select one value, repeat this until we select at least 3 values.
3. After close at console we have logged selected records, and those records should be array of object but instead we are getting array of string.

**Expected behavior**
It should provide array of object.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
As we deals with ids and because if this issue when we get array of string we can't get id assigned to object.

**Comment by tmcconechy** [comment] 2021-02-09 14:56
I dont think we can change this at this time. The Dirty event is just firing and giving you the string thats in the lookup field. That cant handle objects.

try watching the change event instead...
```
this.element.val(value.join(this.settings.delimiter)).trigger('change', [this.selectedRows]);
```

I think this should give you the selectedRows object. Feel free to close if that works.

**Comment by JangleShubham** [comment] 2021-02-11 04:40
Hello Tim,

We are using change event already, please see URL: https://github.com/JangleShubham/enterprise-ng/blob/master/src/app/lookup/lookup.demo.html#L218 
Please take latest code of https://github.com/JangleShubham/enterprise-ng.git and see, we have commented dirty and pristine events but still we are getting same output in console.
Please let us know if we are doing something incorrect.

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-02-11 15:12
I think the only thing "incorrect" is you dont use unique ID's so you cant use the value as a string. I did think that the change event would have objects but i was wrong...

What about using the selected event? 

https://github.com/infor-design/enterprise-ng/blob/master/src/app/lookup/lookup-dialog.demo.html#L4
https://github.com/infor-design/enterprise-ng/blob/master/src/app/lookup/lookup-dialog.demo.ts#L34

?

**Comment by JangleShubham** [comment] 2021-02-15 05:13
Hello Tim,
https://github.com/infor-design/enterprise-ng/blob/master/src/app/lookup/lookup-dialog.demo.html#L4
https://github.com/infor-design/enterprise-ng/blob/master/src/app/lookup/lookup-dialog.demo.ts#L34
This event seems to be off DataGridView, can you please suggest us how to use it in lookup multiselect?
Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-02-16 14:41
Hmm yes your right. This example i think is just "left out" and shows datagrid. Im not seeing a selected event you can access on the lookup. But you can try to get to the underlying example  maybe.

Perhaps a solution here is to expose the selected event in the datagrid to the lookup. This will require some work we will have to schedule down the line. Perhaps you can find a workaround meanwhile on your end (using strings). I'm out of ideas than that for the moment

**Comment by katieinfor** [comment] 2021-04-28 18:25
@dhumalkishor Can you please tell us what team you're on? Thanks!

**Comment by dhumalkishor** [comment] 2021-04-29 13:18
Infor GRC

**Comment by tmcconechy** [comment] 2021-05-11 13:57
I can try and add it to next version but we are moving to quarterly releases so will be end of Q3. I think a possible fix is to use the settings we added as intended. i.e.

Set the field and the match option https://github.com/infor-design/enterprise/blob/main/src/components/lookup/lookup.js#L916

https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-custom-matching.html#L50-L53

I think you might be able to just use that. If you can put the example up in a stack blitz https://stackblitz.com/edit/ids-quick-start-950 fork i can fork it and try it out for you.

Here is the running example: https://main-enterprise.demo.design.infor.com/components/lookup/test-custom-matching.html

**Comment by dhumalkishor** [comment] 2021-05-11 14:07
In which version we get above mentioned code?

**Comment by JangleShubham** [comment] 2021-05-13 05:57
Hello Tim,

We checked with latest SOHO version and tried with stackbliz code you shared.
We are getting results in array now but we have found three issues with it as below:

1. Shows all records selected if duplicate field is same
Steps:
i. Go to page https://ids-quick-start-950-wqyk9n.stackblitz.io/lookup
ii. Click on "Soho miltiselect issue" lookup
iii. Select any two records of column"Application Instance Name" named "Soxtest" and click Apply
iv. Again, click on same lookup, you will find all records named "Soxtest" are selected
Expected: Records selected in steps iii should only be selected in step iv. you suggested match function, how can we use it here?

2. Shows all records selected on second page:
steps:
i. Go to page: https://ids-quick-start-950-wqyk9n.stackblitz.io/lookup
ii. Click on "Soho miltiselect issue" lookup
iii. Select any two records and click on next page button of pagination
iv. At second page, you will find all records are selected
Expected: Only earlier selected records should show selected, (if no records then no records should be selected).

3. Removes already selected entries if we don't visit selected record page:
steps:
i. Go to page: https://ids-quick-start-950-wqyk9n.stackblitz.io/lookup
ii. Click on "Soho miltiselect issue" lookup
iii. Go to second page and select any two records and click Apply.
iv. Again click on same lookup and click on Apply without visiting second page.
v. Selected Records from page two will not be there in the list showed below lookup.
Expected: Whether user travels the page of record or not lookup should return those records as well.

If there is some turnaround for all this please let us know.

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-05-13 13:54
Did you checkout the match example? Basically it's just a function that you set the code in the settings it runs when trying to find the selected items.
https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-custom-matching.html#L54

Is it possible to make a very simple example that just shows the problem (seems like a lot in this one and im not sure where the code is?)

My other suggestions/ideas would be to use a unique key here for matching. Or maybe even use the multiselect https://master-enterprise.demo.design.infor.com/components/multiselect/example-index.html

**Comment by JangleShubham** [comment] 2021-05-17 13:44
Hello Tim,

Thanks for the suggestion, we tried match function and used one more column for matching data.
But following issues are there that we noticed, can we use any property or function to resolve those issues?
Issues noticed are as follows:
	First one is same as 3rd one noticed in my previous comment is still there even after using match function.
	1. Removes already selected entries if we don't visit selected record page:
		steps:
		i. Go to page: https://ids-quick-start-950-wqyk9n.stackblitz.io/lookup
		ii. Click on "Soho miltiselect issue" lookup
		iii. Go to second page and select any two records and click Apply.
		iv. Again click on same lookup and click on Apply without visiting second page.
		v. Selected Records from page two will not be there in the list showed below lookup.
		Expected: Whether user travels the page of record or not lookup should return those records as well.
	
	2. Selected records doesn't appear selected.
		steps:
		i. Go to page: https://ids-quick-start-950-wqyk9n.stackblitz.io/lookup
		ii. Click on "Soho miltiselect issue" lookup.
		iii. Select any two records from first page, then select any two from second page and select any two from third page and click on Apply.
		iv. It will show 6 records selected as expected, but when you open lookup again and visit second page and then third page it will not show selected records of third page.
		v. Also after you click Apply, records from only first page is there in the selected list which is iterated below lookup.
		Expected: Records from all pages should be visible selected after reopening lookup.
		
We have updated code on below link:
https://stackblitz.com/edit/ids-quick-start-950-wqyk9n

Please verify and let us know if there is any mistake we are doing.

Thanks,
Shubham Jangle

**Comment by dhumalkishor** [comment] 2021-05-17 13:47
Hi Tim,

We can't use multiselect in GRC because we have more than 500 records and it will be difficult for user to find the records which they want to select.

Regards,
Kishor

**Comment by tmcconechy** [comment] 2021-05-17 13:51
OK this issue seems like its going to be difficult to resolve due to your ID requirements. We will have to schedule some time for it next sprint for further deeper investigation. We might have to introduce some sort of a fix / setting but not sure how that would look.

You probably could use multiselect with 500 records if you wanted to because you can type to search. But im at a loss for other workarounds for you.  I'm not seeing any obvious solutions other than those.

We might have to introduce some sort of a fix.

**Comment by tmcconechy** [comment] 2021-05-17 13:53
To the person that picks this up - just focus on finding a solution to make https://github.com/infor-design/enterprise-ng/issues/986#issuecomment-842336527 work.

**Comment by tmcconechy** [comment] 2021-07-07 17:55
Just a brief update. I think to fix this we will expose two events 'selected' and 'afterpaging'. With that you should be able to save the selected row's id somehow and then restore them for the page on after paging.

This whole problem is because your using a field that is not unique. So one workaround to get this working now is to change the grid to use `field: 'id'`. I dont suppose that would work good enough for you?

Other workarounds are:

- making the field unique even if its the key or not
- not using serverside paging, using client side paging instead and not using selectAcrossPages

If you think about it there is no way for it to find on the current page what to select if its not unique but the new events should give a way. Will push this soon.

**Comment by dhumalkishor** [comment] 2021-07-08 13:20
Hi Tim,

We have field ID's unique for each field. Not sure about using client side pagination because we have thousands of records so it may impact on performance side. 

Regards,
Kishor

**Comment by tmcconechy** [comment] 2021-07-08 13:27
It should still be pretty fast with 1000s with client side paging. But regarding ID's what i mean is you can show the `id` in the field not the `applicationInstanceName` which is not unique. Then it works.

Nonetheless im adding two events so you can make this work but it is quite a bit more code for you to make it work with non unique values in the field. Will push it soon

**Closed** 2021-07-13 13:45 UTC
Labels: Team: GRC, [5], priority: high, type: enhancement :sparkles:

**Comment by tmcconechy** [comment] 2021-07-13 21:14
@dhumalkishor this should be working now. we had to add an example with NON unique ids in the field.

I still think you should use the component as intended but we exposed afterpaging and selected so you can store your own ID's and it it manually. 

See the new example:
https://github.com/infor-design/enterprise-ng/blob/main/src/app/lookup/lookup-desc.demo.ts
https://github.com/infor-design/enterprise-ng/blob/main/src/app/lookup/lookup-desc.demo.html

You can do it this way or you could just use field: `id`.. Hope this helps

Also these events are in 10.2.0 and 4.53.2

**Comment by JangleShubham** [comment] 2021-07-14 08:04
Hello @tmcconechy ,

Thanks for the extra events to handle this. It seems to be working.
However we found one small issue. When there is single record selected and we unselect that record then at that time selected event does not get invoke.
This results variable previouslySelectedRows contains that one last value even after deselecting all the values.
As we need results in object format, so we need variable previouslySelectedRows for further operations as per business requirements.

Thanks,
Shubham Jangle

**Comment by dhumalkishor** [comment] 2021-07-14 13:19
Hi Tim,

We found one more issue with multiselect lookup. Please refer below steps to reproduce the same.

1. Go to "http://localhost:4200/ids-enterprise-ng-demo/lookup-desc"
2. Click on browse button and select first record of the first page
3. Go to 2nd page and select first records and click on Apply.
4. Now again click on browse button and uncheck the first page record and click on apply button.
5. See both records are got removed. 

It should remove only one record.

Regards,
Kishor

**Comment by tmcconechy** [comment] 2021-07-14 13:46
@deep7102 do you want to look into these two cases or should I? Thanks

**Comment by deep7102** [comment] 2021-07-14 13:50
Do you have any idea what it could be caused otherwise I can look into

[Infor]<http://www.infor.com/>
Deepak Verma | Senior Software Engineer | Infor Design
mobile: 856 426 1110 | ***@***.******@***.***> | design.infor.com<https://design.infor.com/>


From: Tim McConechy ***@***.***>
Reply-To: infor-design/enterprise-ng ***@***.***>
Date: Wednesday, July 14, 2021 at 9:46 AM
To: infor-design/enterprise-ng ***@***.***>
Cc: Deepak Verma ***@***.***>, Mention ***@***.***>
Subject: Re: [infor-design/enterprise-ng] Lookup: In multiselect we are getting array of string instead of array of object (#986)

Sent by an external sender
------------------------------------


@deep7102<https://github.com/deep7102> do you want to look into these two cases or should I? Thanks

**Comment by tmcconechy** [comment] 2021-07-14 13:52
No not yet needs to be investigated by one of us. Since i can connect very well right now can you have a look? Ideally we just can update the example and make it work

**Comment by deep7102** [comment] 2021-07-14 13:54
Sure! Let’s me see.

[Infor]<http://www.infor.com/>
Deepak Verma | Senior Software Engineer | Infor Design
mobile: 856 426 1110 | ***@***.******@***.***> | design.infor.com<https://design.infor.com/>


From: Tim McConechy ***@***.***>
Reply-To: infor-design/enterprise-ng ***@***.***>
Date: Wednesday, July 14, 2021 at 9:52 AM
To: infor-design/enterprise-ng ***@***.***>
Cc: Deepak Verma ***@***.***>, Mention ***@***.***>
Subject: Re: [infor-design/enterprise-ng] Lookup: In multiselect we are getting array of string instead of array of object (#986)

Sent by an external sender
------------------------------------


No not yet needs to be investigated by one of us. Since i can connect very well right now can you have a look? Ideally we just can update the example and make it work

**Comment by nganotice** [comment] 2021-07-22 10:12
This has been QA tested and passed on v4.54.0-dev.

https://main-enterprise.demo.design.infor.com/components/lookup/test-multiselect-description-only.html 
![Screen Shot 2021-07-22 at 6 12 31 PM](https://user-images.githubusercontent.com/84306838/126623651-c95b52c0-a099-410a-802e-0585fdaffbe5.png)

Moving this ticket to Done.

Thanks!

**Comment by tmcconechy** [comment] 2021-07-22 15:09
@dhumalkishor and @JangleShubham all additional fixes are merged and patched into 4.53.4 also made an NG version patch with the fix https://www.npmjs.com/package/ids-enterprise-ng/v/10.2.1

**Comment by CindyMercadoReyes** [comment] 2021-07-23 18:50
This issue is now resolved.

**Comment by JangleShubham** [comment] 2021-07-26 12:27
Hello @tmcconechy ,

Thanks for the update and issues reported last time seems to be resolved.
But there is one small issue observe (maybe we are missing some step).

In GRC application, when we select records, it gets displayed below the lookup control as a soho list view and this list view has a cancel/delete button as well.
This means user can unselect the record before opening the model popup grid by clicking on that button.
It is shown in below image:

![image](https://user-images.githubusercontent.com/50510865/126988479-a4d0858d-9825-48ab-8cc9-63c5194cb853.png)

We have iterated the list we get in event (selected) and used as onSelected in component level.
We are getting values by using code:
this.previouslySelectedRows = e.selectedRows?.slice();

When user click on cancel/delete button of list, we have removed the items from list this.previouslySelectedRows and also from array model.desc(ngModel).
And after clicking on lookup we iterate this.previouslySelectedRows to show selected records as below (The code is written in event (afterpaging)):
e.lookup.grid.unSelectAllRows(true);
for (const selectedRow of this.previouslySelectedRows) {
  alert(selectedRow.data.id)
  e.lookup.selectRowByValue('id', selectedRow.data.id);
}

But after this as well it shows those records which were cancelled/deleted.
It doesn't appear in e.selectedRows but it shows as selected in grid after opening.

Are we missing something?
If there is any event/function already present to handle this, please let us know.

Please let us know if more details required from our side.

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-07-26 13:19
@JangleShubham wha you just added i dont 100% follow. I think we should make a follow up issue with simple steps to reproduce? I dont get how its got now a "lookup control as a soho list view and this list view has a cancel/delete button as well.". This seems like something entirely new.

But anyways this issue is already very confusing so lets start with a new issue. If its small i'd like to save it for later

**Comment by JangleShubham** [comment] 2021-07-26 13:41
Hello @tmcconechy ,

In short we just want a way to unselect the record without opening lookup popup.
We are removing a record we want to remove from list this.previouslySelectedRows and also from model.desc, but still after opening model popup those records shows selected.

We are using below code to show selected records in afterpaging event:
e.lookup.grid.unSelectAllRows(true);
for (const selectedRow of this.previouslySelectedRows) {
e.lookup.selectRowByValue('id', selectedRow.data.id);
}

I think we should we go with same issue as we can't go ahead with this issue.

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-07-26 13:44
OK whats the part about listview? thats what is confusing. Can you modify the existing example

**Comment by deep7102** [comment] 2021-07-26 13:59
Hi @JangleShubham I think instead of use that `previouslySelectedRows[]`, it should sync with `lookupApi.selectedRows[]`. Because lookup modal take selected rows from `lookupApi.selectedRows[]` array before open the modal.

**Comment by JangleShubham** [comment] 2021-07-26 14:21
Hello @tmcconechy / @deep7102 ,
We have forked the code and added our code in **https://github.com/JangleShubham/enterprise-ng**, in file src/app/lookup/lookup-desc.demo.ts and src/app/lookup/lookup-desc.demo.html.
We are unselecting/removing record in method **delSelectedTree**
Could you please tell how do we use lookup API there?

@dhumalkishor can you explain use case for this?

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-07-26 14:24
Thanks first did you try @deep7102 answer. That actually sounds like it could work. https://github.com/infor-design/enterprise-ng/issues/986#issuecomment-886728054

**Comment by JangleShubham** [comment] 2021-08-03 04:48
Hello @tmcconechy and @deep7102 ,
Thanks for the solution. Solution suggested is seems to be working, we are in process of integrating it in GRC now.
Thanks for your help.
Regards,
Shubham Jangle

**Comment by tmcconechy** [comment] 2021-08-03 13:34
Your welcome, were glad it works now 😓 👍🏻
