### ISSUE TITLE
Tabs: Outline of active tab is cut at the bottom

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-ng#1246] opened 2022-03-02 04:46 UTC
**Describe the bug**
Outline of active tab is cut at the bottom. The outline is completely shown in [4.52.0](https://design.infor.com/code/ids-enterprise/4.52.0/demo/components/tabs-module/example-index.html).

**To Reproduce**
1. Go to [this demo](https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/tabs-module/example-index.html)
2. Click on the "New Tab Builder"
3. You can observe that the white outline at the bottom is no longer visible

**Expected behavior**
The white outline at the bottom is visible

**Version**
- ids-enterprise: 4.60.0

**Screenshots**
![image](https://user-images.githubusercontent.com/55830499/156296747-661c091f-5a6e-4266-a26f-155dcf5f0e1c.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 98.0.4758.102 (Official Build) (64-bit)

**Comment by yohannahbautista** [comment] 2022-10-04 06:07
@inforrpunay  @tmcconechy @ericangeles 
Hello, I checked main and the full outline shows. I found the solution here: https://github.com/infor-design/enterprise/blob/main/src/components/tabs/tabs.js#L3875
Should I add it to branch 4.60.x?

**Comment by ericangeles** [comment] 2022-10-04 09:47
@yohannahbautista please make a PR (4.68.x)

**Comment by ericangeles** [comment] 2022-10-04 09:54
@inforrpunay it's now fixed in the current version. Suppose you requested to make a patch for 4.60.x, we'll schedule it.

**Comment by tmcconechy** [comment] 2022-10-04 14:31
@ericangeles @yohannahbautista i think its going to be hard to patch 4.60.x because all the infrastructure wasn't in place.
We generally only patch one or two versions back (so 4.67/4.66) are possible

**Comment by ericangeles** [comment] 2022-10-04 14:35
So I guess @inforrpunay should update his version of IDS.

**Comment by ericangeles** [comment] 2022-10-21 06:17
Closing this as the issue is already resolved.

**Closed by ericangeles** 2022-10-21 06:17 UTC
Labels: type: bug :bug:, [2], team: m3
