### ISSUE TITLE
Blockgrid component: Index returning as NaN

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-ng#748] opened 2020-02-27 11:18 UTC
**Describe the bug**
I have a scenario where my functionality is tied to the index given by the event of selecting a blockgrid. But I noticed after upgrading ids-enterprise-ng from 5.0.0 to 6.1.1 it stopped working due to the index returns as NaN for the blockgrid component. From what i can see this issue is only when using the enterprise-ng. 

**To Reproduce**
**Working scenario in ids-enterprise:**
1. Go to https://master-enterprise.demo.design.infor.com/components/blockgrid/example-singleselect.html
2. Select a block in the grid
3. Check the console in browser developer tools
4. Notice how selectedRows contains the idx attribute and it does have a proper value.

**Broken scenario in ids-enterprise-ng:**
1. Start https://github.com/infor-design/enterprise-ng
2. Go to blockgrid Single select example
3. Select a block in the grid
4. Check the console in browser developer tools
5. Notice how selectedRows contains the idx attribute but it is showing as NaN.

**Expected behavior**
The event of selecting a block in the blockgrid component should return the proper index(idx) value.

**Version**
- ids-enterprise-ng: 6.1.1

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9215760/75439457-1dcb1a80-595a-11ea-8f10-9d6477e90b42.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9215760/75439459-1efc4780-595a-11ea-92fc-ddabbd5a84eb.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 80.0.3987.116 (Official Build) (64-bit)

**Trivial bonus Issue**
I noticed the warning for selectBlock() deprication in all of our applications.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9215760/75439700-93cf8180-595a-11ea-9a3f-22d6552deec5.png)

But I cannot find any references to selectBlock() in any of our code. Looks like your own code is triggering the deprication warning?

**Comment by tmcconechy** [comment] 2020-03-03 20:42
@Carlfjord I pushed a fix for these two things. But with respect to the missing index. There is a "workaround".  In the enterprise example we actually pass in an ID in the data and you can read that but the NG example does have that. So if you use the data you can reference it as you want https://github.com/infor-design/enterprise/blob/master/app/views/components/blockgrid/example-singleselect.html#L16 buy simply putting something on the data.id for each row.

**Closed** 2020-03-04 14:22 UTC
Labels: [1], type: bug :bug:

**Comment by jbrcna** [comment] 2020-03-05 11:31
QA PASSED. the issue is now resolved.
verified in master-enterprise
v4.27.0-dev
