### ISSUE TITLE
Infor logo not displayed at bottom of application menu

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#484] opened 2019-05-15 11:44 UTC
**Describe the bug**

The Infor icon is not pinned to the bottom of the Application Menu.

**To Reproduce**

Clone the ids-enterprise-ng repo.
```sh
npm run build:lib
npm run start
```

Navigate to `http://localhost:4200/ids-enterprise-ng-demo/`

**Expected behavior**

The Infor icon should be attached to the bottom of the container, also if the Search field is added it should not push the logo off the bottom.

**Version**
- ids-enterprise-ng: 5.3.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/57773146-380b7300-770f-11e9-8838-1c2a56c4d729.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2019-05-15 13:00
Duplicate of https://github.com/infor-design/enterprise/issues/2116 (will fix and there is a workaround noted)

**Closed by tmcconechy** 2019-05-15 13:00 UTC
