### ISSUE TITLE
Using *ngIf on a soho-menu-button throws a JS error when clicked

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise-ng#268] opened 2018-11-09 19:22 UTC
**Describe the bug**
On **4.12.x**, if an *ngIf condition toggles (shows/hides) a "soho-menu-button" the following JS error is thrown when the button is clicked after being toggled.

This didn't happen on **4.10.x** neither on **4.5.x**.

`
zone.js:192 Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at PopupMenu.position (sohoxi.js:10104)
    at PopupMenu.open (sohoxi.js:10402)
    at doOpen (sohoxi.js:9571)
    at contextMenuHandler (sohoxi.js:9593)
    at HTMLButtonElement.<anonymous> (sohoxi.js:9600)
    at HTMLButtonElement.dispatch (jquery.js:5183)
    at HTMLButtonElement.elemData.handle (jquery.js:4991)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
`

**To Reproduce**
1. Check out "enterprise-ng" 4.12.x
2. Edit the "soho-menu-button" example to add a plain "*nIf" condition `<button *ngIf="toggle" soho-menu-button ...>` where "toggle" is a boolean.
3. Add a helper button which would change the value of "toggle" between true and false.
3. Build and serve the application and visit the example page.
4. Click on the helper button to toggle on/off the menu-button then, click on the menu-button.
5. Look for the errors in the developer tools console.

**Expected behavior**
The men-button should work normally after being hidden/shown and display its corresponding menu.

**Comment by edgarinfor** [comment] 2018-11-09 19:23
Hi, @bthharper, could this be related to the ngZone changes?

**Comment by bthharper** [comment] 2018-11-13 09:38
This is a duplicate of #84.

**Comment by tmcconechy** [comment] 2019-03-07 16:50
Closing as a duplicate

**Closed by tmcconechy** 2019-03-07 16:50 UTC
Labels: status: duplicate
